### ISSUE TITLE
bug: error An unexpected error occurred

### ISSUE THREAD

**Issue by Cide999** [spacebarchat/docker#9]
Maybe someone deleted this project.
![Snipaste_2023-08-07_23-50-19](https://github.com/spacebarchat/docker/assets/30822042/8b7b8530-cb8f-4594-bbbb-2604a3da80bf)

```
[+] Building 34.5s (17/18)
 => [internal] load .dockerignore                                                                                                                                                                           0.1s
 => => transferring context: 2B                                                                                                                                                                             0.0s
 => [internal] load build definition from Dockerfile-frontend                                                                                                                                               0.2s
 => => transferring dockerfile: 906B                                                                                                                                                                        0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                                                                 19.2s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:ac85f380a63b13dfcefa89046420e1781752bab202122f8f50032edf31be0021                                                                             0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                                                                                             8.7s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                                             7.8s
 => [internal] load build context                                                                                                                                                                           0.1s
 => => transferring context: 39B                                                                                                                                                                            0.0s
 => [builder 1/9] FROM docker.io/library/ubuntu:22.04@sha256:0bced47fffa3361afa981854fcabcd4577cd43cebbb808cea2b1f33a3dd7f508                                                                               0.0s
 => CACHED [stage-1 1/2] FROM docker.io/library/nginx:alpine@sha256:2d194184b067db3598771b4cf326cfe6ad5051937ba1132b8b7d4b0184e0d0a6                                                                        0.0s
 => CACHED [builder 2/9] RUN apt update ; apt install -y curl git gnupg2 ;                                                                                                                                  0.0s
 => CACHED [builder 3/9] RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -                                                                                                              0.0s
 => CACHED [builder 4/9] RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list                                                                                  0.0s
 => CACHED [builder 5/9] RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -                                                                                                                        0.0s
 => CACHED [builder 6/9] RUN apt update ; apt install -y yarn nodejs                                                                                                                                        0.0s
 => CACHED [builder 7/9] RUN git clone https://github.com/Casraw/spacebarchat-client.git ; cd spacebarchat-client ; git checkout master                                                                     0.0s
 => CACHED [builder 8/9] COPY script-frontend.sh spacebarchat-client/script-frontend.sh                                                                                                                     0.0s
 => ERROR [builder 9/9] RUN cd spacebarchat-client && chmod +x script-frontend.sh &&  sed -i -e 's/\r$//' script-frontend.sh && ./script-frontend.sh && yarn install && yarn build:web                      5.9s
------
 > [builder 9/9] RUN cd spacebarchat-client && chmod +x script-frontend.sh &&  sed -i -e 's/\r$//' script-frontend.sh && ./script-frontend.sh && yarn install && yarn build:web:
#0 0.862 yarn install v1.22.19
#0 0.953 [1/4] Resolving packages...
#0 5.724 error An unexpected error occurred: "https://registry.yarnpkg.com/@puyodead1%2ffosscord-api-types: Not found".
#0 5.725 info If you think this is a bug, please open a bug report with the information provided in "/spacebarchat-client/yarn-error.log".
#0 5.725 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c cd spacebarchat-client && chmod +x script-frontend.sh &&  sed -i -e 's/\\r$//' script-frontend.sh && ./script-frontend.sh && yarn install && yarn build:web" did not complete successfully: exit code: 1
```

**Comment by Cide999** [comment]
![Snipaste_2023-08-07_23-54-20](https://github.com/spacebarchat/docker/assets/30822042/3b3ec43c-6f1b-4ea9-8a30-b574b6fee0c6)

**Comment by Puyodead1** [comment]
🫣

**Comment by Puyodead1** [comment]
It's under `@spacebarchat/spacebar-api-types` now

**Comment by Cide999** [comment]
> It's under `@spacebarchat/spacebar-api-types` now

Can you please let me know when the link will be fixed or how to fix it? I am still getting an error while setting up docker.

**Comment by Cide999** [comment]
> > > It's under `@spacebarchat/spacebar-api-types` now 现在已经下了
> > 
> > 
> > Can you please let me know when the link will be fixed or how to fix it? I am still getting an error while setting up docker. Thank you. XD
> 
> I forgot about this, are you cloning the repo and building the docker image or just pulling from docker hub?
> 
> You should not be getting this error, it was fixed a while ago in the client repo, and its suppose to pull the latest version

I cloned the entire code from GitHub, then I wrote an environment variable file in the spacebar-server-client-proxy directory, and finally executed this command:
docker-compose --env-file=.env -f docker-compose.prod.yaml up -d
Pulling images definitely comes from Docker Hub, so the question is whether the issue lies with the images on Docker Hub? Are you suggesting that we need to manually create a Docker image in order to avoid this error?

**Comment by Puyodead1** [comment]
> > > > It's under `@spacebarchat/spacebar-api-types` now
> > > 
> > > 
> > > Can you please let me know when the link will be fixed or how to fix it? I am still getting an error while setting up docker. Thank you. XD
> > 
> > 
> > I forgot about this, are you cloning the repo and building the docker image or just pulling from docker hub?
> > You should not be getting this error, it was fixed a while ago in the client repo, and its suppose to pull the latest version
> 
> I cloned the entire code from GitHub, then I wrote an environment variable file in the spacebar-server-client-proxy directory, and finally executed this command: docker-compose --env-file=.env -f docker-compose.prod.yaml up -d Pulling images definitely comes from Docker Hub, so the question is whether the issue lies with the images on Docker Hub? Are you suggesting that we need to manually create a Docker image in order to avoid this error?

yes, I was asking if you were building the image or pulling it. I am assuming that the image on docker hub is outdated

**Comment by Puyodead1** [comment]
I did change something though and it triggered a rebuild, but it seems stuck waiting

**Comment by Cide999** [comment]
> I did change something though and it triggered a rebuild, but it seems stuck waiting

I gradually understand what you mean. This error occurred during the build process. In the Docker Compose configuration file on GitHub, spacebar, nginx, and spacebar-client are all built, while only the db database is pulled. I have tried deleting all containers, images, and volumes related to spacebar, then pulling this code from GitHub again and rebuilding it. However, the same error still occurs in the end.
Maybe I should consider reinstalling the operating system.XD

**Comment by Puyodead1** [comment]
> > I did change something though and it triggered a rebuild, but it seems stuck waiting
> 
> I gradually understand what you mean. This error occurred during the build process. In the Docker Compose configuration file on GitHub, spacebar, nginx, and spacebar-client are all built, while only the db database is pulled. I have tried deleting all containers, images, and volumes related to spacebar, then pulling this code from GitHub again and rebuilding it. However, the same error still occurs in the end. Maybe I should consider reinstalling the operating system.XD

just running docker compose will still pull from docker hub. you have to actually build the image first

**Comment by Puyodead1** [comment]
new build has been pushed to docker hub

**Comment by Cide999** [comment]
> > > I did change something though and it triggered a rebuild, but it seems stuck waiting
> > 
> > 
> > I gradually understand what you mean. This error occurred during the build process. In the Docker Compose configuration file on GitHub, spacebar, nginx, and spacebar-client are all built, while only the db database is pulled. I have tried deleting all containers, images, and volumes related to spacebar, then pulling this code from GitHub again and rebuilding it. However, the same error still occurs in the end. Maybe I should consider reinstalling the operating system.XD
> 
> just running docker compose will still pull from docker hub. you have to actually build the image first

Do you mean using this command to build?
docker build -t=ubuntu:22.04 .

**Comment by Cide999** [comment]
> > > I did change something though and it triggered a rebuild, but it seems stuck waiting
> > 
> > 
> > I gradually understand what you mean. This error occurred during the build process. In the Docker Compose configuration file on GitHub, spacebar, nginx, and spacebar-client are all built, while only the db database is pulled. I have tried deleting all containers, images, and volumes related to spacebar, then pulling this code from GitHub again and rebuilding it. However, the same error still occurs in the end. Maybe I should consider reinstalling the operating system.XD
> 
> just running docker compose will still pull from docker hub. you have to actually build the image first

I know what's causing this bug. The issue lies in the Dockerfile-frontend at https://github.com/Casraw/spacebarchat-client.git.
In this project, all the links related to spacebarchat are written as @puyodead1/fosscord-api-types.
If you know @Casraw , please inform him to make the necessary changes.
Thank you! XD

**Comment by Puyodead1** [comment]
> > > > I did change something though and it triggered a rebuild, but it seems stuck waiting
> 
> > > 
> 
> > > 
> 
> > > I gradually understand what you mean. This error occurred during the build process. In the Docker Compose configuration file on GitHub, spacebar, nginx, and spacebar-client are all built, while only the db database is pulled. I have tried deleting all containers, images, and volumes related to spacebar, then pulling this code from GitHub again and rebuilding it. However, the same error still occurs in the end. Maybe I should consider reinstalling the operating system.XD
> 
> > 
> 
> > just running docker compose will still pull from docker hub. you have to actually build the image first
> 
> 
> 
> I know what's causing this bug. The issue lies in the Dockerfile-frontend at https://github.com/Casraw/spacebarchat-client.git.
> 
> In this project, all the links related to spacebarchat are written as @puyodead1/fosscord-api-types.
> 
> If you know @Casraw , please inform him to make the necessary changes.
> 
> Thank you! XD

Where is that from though?

**Comment by Cide999** [comment]
> > > > > I did change something though and it triggered a rebuild, but it seems stuck waiting
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I gradually understand what you mean. This error occurred during the build process. In the Docker Compose configuration file on GitHub, spacebar, nginx, and spacebar-client are all built, while only the db database is pulled. I have tried deleting all containers, images, and volumes related to spacebar, then pulling this code from GitHub again and rebuilding it. However, the same error still occurs in the end. Maybe I should consider reinstalling the operating system.XD
> > 
> > 
> > > 
> > 
> > 
> > > just running docker compose will still pull from docker hub. you have to actually build the image first
> > 
> > 
> > I know what's causing this bug. The issue lies in the Dockerfile-frontend at https://github.com/Casraw/spacebarchat-client.git.
> > In this project, all the links related to spacebarchat are written as @puyodead1/fosscord-api-types.
> > If you know @Casraw , please inform him to make the necessary changes.
> > Thank you! XD
> 
> Where is that from though?

![Snipaste_2023-08-24_20-27-26](https://github.com/spacebarchat/docker/assets/30822042/d49553dd-1d27-4246-b62c-3a6d4dd1b755)
![Snipaste_2023-08-24_20-28-24](https://github.com/spacebarchat/docker/assets/30822042/29383bd6-a4bf-408c-80a2-5f830b4c9a72)
![Snipaste_2023-08-24_20-28-55](https://github.com/spacebarchat/docker/assets/30822042/1c06fc28-0b28-4922-a6ca-dce19bc11067)

**Comment by Puyodead1** [comment]
> > > > > > I did change something though and it triggered a rebuild, but it seems stuck waiting
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > I gradually understand what you mean. This error occurred during the build process. In the Docker Compose configuration file on GitHub, spacebar, nginx, and spacebar-client are all built, while only the db database is pulled. I have tried deleting all containers, images, and volumes related to spacebar, then pulling this code from GitHub again and rebuilding it. However, the same error still occurs in the end. Maybe I should consider reinstalling the operating system.XD
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > just running docker compose will still pull from docker hub. you have to actually build the image first
> > > 
> > > 
> > > I know what's causing this bug. The issue lies in the Dockerfile-frontend at https://github.com/Casraw/spacebarchat-client.git.
> > > In this project, all the links related to spacebarchat are written as @puyodead1/fosscord-api-types.
> > > If you know @Casraw , please inform him to make the necessary changes.
> > > Thank you! XD
> > 
> > 
> > Where is that from though?
> 
> ![Snipaste_2023-08-24_20-27-26](https://user-images.githubusercontent.com/30822042/262972509-d49553dd-1d27-4246-b62c-3a6d4dd1b755.png) ![Snipaste_2023-08-24_20-28-24](https://user-images.githubusercontent.com/30822042/262972602-29383bd6-a4bf-408c-80a2-5f830b4c9a72.png) ![Snipaste_2023-08-24_20-28-55](https://user-images.githubusercontent.com/30822042/262972647-1c06fc28-0b28-4922-a6ca-dce19bc11067.png)

wtf, ok I didnt know that. I have no clue why thats setup that way either

**Comment by Puyodead1** [comment]
oh, they have a custom script in it guess, sigh

**Comment by Puyodead1** [comment]
alr, I fixed it. it uses the official repo now

**Comment by Puyodead1** [comment]
> I'm sorry, but I've found another new bug. XD It seems that the official project does not have a .env file. ![Snipaste_2023-08-24_20-55-15](https://user-images.githubusercontent.com/30822042/262979416-99606c25-6271-4420-a23c-bf5e160ee5f0.png)

AAA, ok I pushed another fix that should work. the docker container should be updated shortly

**Comment by Cide999** [comment]
> > I'm sorry, but I've found another new bug. XD It seems that the official project does not have a .env file. ![Snipaste_2023-08-24_20-55-15](https://user-images.githubusercontent.com/30822042/262979416-99606c25-6271-4420-a23c-bf5e160ee5f0.png)
> 
> AAA, ok I pushed another fix that should work. the docker container should be updated shortly

It works.
Thank you!
![Snipaste_2023-08-24_21-21-22](https://github.com/spacebarchat/docker/assets/30822042/b7d0b4c2-92be-49a8-b735-487ada515c2c)

**Comment by Puyodead1** [comment]
👍🏻
